### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by AnkushRoy7926** [Granted07/Whatsapp-Spammer#1]
Line number 97 in whatsapp.py

```
Traceback (most recent call last):
  File "/home/lordraleigh/Downloads/Whatsapp-Spammer-New-main/main.py", line 3, in <module>
    from whatsapp import returnDictData, send_message
  File "/home/lordraleigh/Downloads/Whatsapp-Spammer-New-main/whatsapp.py", line 97
    open('flagged.txt', 'a').write(f'{link.split('B')[1][2:12]}\n')
                                                                  ^
SyntaxError: f-string: unmatched '('
```

Change this line -

`open('flagged.txt', 'a').write(f'{link.split('B')[1][2:12]}\n')`

to this - 

`open('flagged.txt', 'a').write(f"{link.split('B')[1][2:12]}\n")`

**Comment by Granted07** [comment]
Solved
